// THIS IS A FILE THAT WAS GENERATED BY A SCRIPT,
// HENCE THE RANDOMLY GENERATED UUID VALUES FOR THE
// ID FIELDS

import { boolean, BooleanSchema } from "yup";

export const deathKnightBlood: BooleanSchema = boolean().required();
export const deathKnightFrost: BooleanSchema = boolean().required();
export const deathKnightUnholy: BooleanSchema = boolean().required();
export const demonHunterHavoc: BooleanSchema = boolean().required();
export const demonHunterVengeance: BooleanSchema = boolean().required();
export const druidBalance: BooleanSchema = boolean().required();
export const druidFeral: BooleanSchema = boolean().required();
export const druidGuardian: BooleanSchema = boolean().required();
export const druidRestoration: BooleanSchema = boolean().required();
export const hunterBeastMastery: BooleanSchema = boolean().required();
export const hunterMarksmanship: BooleanSchema = boolean().required();
export const hunterSurvival: BooleanSchema = boolean().required();
export const mageArcane: BooleanSchema = boolean().required();
export const mageFire: BooleanSchema = boolean().required();
export const mageFrost: BooleanSchema = boolean().required();
export const monkBrewmaster: BooleanSchema = boolean().required();
export const monkMistweaver: BooleanSchema = boolean().required();
export const monkWindwalker: BooleanSchema = boolean().required();
export const paladinHoly: BooleanSchema = boolean().required();
export const paladinProtection: BooleanSchema = boolean().required();
export const paladinRetribution: BooleanSchema = boolean().required();
export const priestDiscipline: BooleanSchema = boolean().required();
export const priestHoly: BooleanSchema = boolean().required();
export const priestShadow: BooleanSchema = boolean().required();
export const rogueAssassination: BooleanSchema = boolean().required();
export const rogueOutlaw: BooleanSchema = boolean().required();
export const rogueSubtlety: BooleanSchema = boolean().required();
export const shamanElemental: BooleanSchema = boolean().required();
export const shamanEnhancement: BooleanSchema = boolean().required();
export const shamanRestoration: BooleanSchema = boolean().required();
export const warlockAffliction: BooleanSchema = boolean().required();
export const warlockDemonology: BooleanSchema = boolean().required();
export const warlockDestruction: BooleanSchema = boolean().required();
export const warriorArms: BooleanSchema = boolean().required();
export const warriorFury: BooleanSchema = boolean().required();
export const warriorProtection: BooleanSchema = boolean().required();
export const specializations = {
  deathKnightBlood,
  deathKnightFrost,
  deathKnightUnholy,
  demonHunterHavoc,
  demonHunterVengeance,
  druidBalance,
  druidFeral,
  druidGuardian,
  druidRestoration,
  hunterBeastMastery,
  hunterMarksmanship,
  hunterSurvival,
  mageArcane,
  mageFire,
  mageFrost,
  monkBrewmaster,
  monkMistweaver,
  monkWindwalker,
  paladinHoly,
  paladinProtection,
  paladinRetribution,
  priestDiscipline,
  priestHoly,
  priestShadow,
  rogueAssassination,
  rogueOutlaw,
  rogueSubtlety,
  shamanElemental,
  shamanEnhancement,
  shamanRestoration,
  warlockAffliction,
  warlockDemonology,
  warlockDestruction,
  warriorArms,
  warriorFury,
  warriorProtection,
};
export const specializationsDefaults = {
  deathKnightBlood: false,
  deathKnightFrost: false,
  deathKnightUnholy: false,
  demonHunterHavoc: false,
  demonHunterVengeance: false,
  druidBalance: false,
  druidFeral: false,
  druidGuardian: false,
  druidRestoration: false,
  hunterBeastMastery: false,
  hunterMarksmanship: false,
  hunterSurvival: false,
  mageArcane: false,
  mageFire: false,
  mageFrost: false,
  monkBrewmaster: false,
  monkMistweaver: false,
  monkWindwalker: false,
  paladinHoly: false,
  paladinProtection: false,
  paladinRetribution: false,
  priestDiscipline: false,
  priestHoly: false,
  priestShadow: false,
  rogueAssassination: false,
  rogueOutlaw: false,
  rogueSubtlety: false,
  shamanElemental: false,
  shamanEnhancement: false,
  shamanRestoration: false,
  warlockAffliction: false,
  warlockDemonology: false,
  warlockDestruction: false,
  warriorArms: false,
  warriorFury: false,
  warriorProtection: false,
};
